---
title: "BSE"
author: "Ranjith G"
date: "15 May 2019"
output: word_document
---
```{r}


library(Quandl)
library(tidyverse)
library(tidyquant)
library(tidyselect)

Quandl.api_key("eFNsb_JDyNQsTKnXc5JN")
```

```{r}
BSE_2019<-Quandl("BSE/SENSEX",collapse="daily",
                 start_date="2019-03-11",end_date="2019-05-23",type="raw")
BSE_2019[2:4]<-NULL
BSE100_2019<-Quandl("BSE/BSE100",collapse="daily",
                    start_date="2019-03-11",end_date="2019-05-23",type="raw")
BSE100_2019[2:4]<-NULL
BSEAUTO_2019<-Quandl("BSE/SI1900",collapse="daily",
                     start_date="2019-03-11",end_date="2019-05-23",type="raw")
BSEAUTO_2019[2:4]<-NULL

```

```{r}
BSE<-cbind(BSE_2019,Stock="")
BSE$Stock<-paste(BSE$Stock,"BSE",sep="")

BSE100<-cbind(BSE100_2019,Stock="")
BSE100$Stock<-paste(BSE$Stock,"BSE100",sep="")

BSEAUTO<-cbind(BSEAUTO_2019,Stock="")
BSEAUTO$Stock<-paste(BSE$Stock,"BSEAUTO",sep="")
```

```{r}
Master_Data<-rbind(BSE,BSE100,BSEAUTO)


Master_Data$Date<-as.character(Master_Data$Date)
list<-strsplit(Master_Data$Date,"-")

library(plyr)
Master_Date1<-ldply(list)
colnames(Master_Date1)<-c("Year","Month","Day")
Master_Data<-cbind(Master_Data,Master_Date1)
names(Master_Data)
Master_Data$Date<-as.Date(Master_Data$Date)
```

```{r}
P<- ggplot(Master_Data,aes(factor(Stock),Close,color=Stock,frame=Month)) +
  geom_jitter(aes(size = Close, colour=Stock, alpha=.02)) +
  ylim(0,40000)+
  labs(title = "BSE Stock Prices", x = "BSE", y= "Close Price") +
  theme(panel.border = element_blank(),
        panel.grid.major = element_line(colour = "grey61", size = 0.5, linetype = "dotted"),
        panel.grid.minor = element_blank(),
        axis.line=element_line(colour="black"),
        plot.title = element_text(hjust = 0.5,size=18,colour="indianred4"))+
  theme(legend.position="none")
P
```

```{r}
Master_Data<-Master_Data%>%
  tibble::as.tibble()%>%
  group_by(Stock)
Master_Data %>%
  ggplot(aes(x = Date, y = Close, color = Stock)) +
  geom_point() +
  labs(title = "Daily Close Price", x = "Month",y="Close Price") +
  facet_wrap(~ Stock, ncol = 3, scale = "free_y") +
  scale_fill_tq(fill="green4",theme="light") +
  theme_tq() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_line(colour = "grey61", size = 0.5, linetype = "dotted"),
        panel.grid.minor = element_blank(),
        axis.line=element_line(colour="black"),
        plot.title = element_text(hjust = 0.5,size=18,colour="indianred4"))+
  theme(legend.position="none")
```

```{r}
#Chart

BSE_2019x<-Quandl("BSE/SENSEX",collapse="daily",
                 start_date="2019-03-11",end_date="2019-05-23",type="xts")

BSE100_2019x<-Quandl("BSE/BSE100",collapse="daily",
                    start_date="2019-03-11",end_date="2019-05-23",type="xts")

BSEAUTO_2019x<-Quandl("BSE/SI1900",collapse="daily",
                     start_date="2019-03-11",end_date="2019-05-23",type="xts")
```

```{r}
chartSeries(BSE_2019x)
```

```{r}
hist(BSE_2019x$Close, breaks=10, col='blue')
```

```{r}
chartSeries(BSE100_2019x, theme="white", TA="addVo();addBBands();addRSI()")
```

#Moving Average
```{r}
BSE_mm <- subset( BSE_2019x, index(BSE_2019x) >= "2019-04-11")

BSE_mm3 <- rollmean(BSE_mm[,4], 6, fill = list(NA, NULL, NA), align = "right")
BSE_mm6 <- rollmean(BSE_mm[,4], 10, fill = list(NA, NULL, NA), align = "right")

BSE_mm$mm3 <- coredata(BSE_mm3)
BSE_mm$mm6 <- coredata(BSE_mm6)
ggplot(BSE_mm, aes(x = index(BSE_mm))) +
  geom_line(aes(y = BSE_mm[,4], color = "BSE")) + ggtitle("BSE MOVING AVERAGE") +
  geom_line(aes(y = BSE_mm$mm3, color = "MM6")) +
  geom_line(aes(y = BSE_mm$mm6, color = "MM10")) + xlab("Date") + ylab("Price") +
  theme(plot.title = element_text(hjust = 0.5), panel.border = element_blank()) +
  scale_x_date(date_labels = "%b %y", date_breaks = "4 months") +
  scale_colour_manual("Series", values=c("BSE"="gray40", "MM6"="firebrick4", "MM10"="darkcyan"))
```


```{r}
BSE_ret <- diff(log(BSE_2019x[,4]))
BSE_ret <- BSE_ret[-1,]


summary(BSE_ret)
```

```{r}

ggplot(BSE_ret, aes(x = index(BSE_ret), y = BSE_ret)) +
  geom_line(color = "deepskyblue4") +
  ggtitle("BSE returns series") +
  xlab("Date") + ylab("Return") +
  theme(plot.title = element_text(hjust = 0.5)) + scale_x_date(date_labels = "%b %y", date_breaks = "1 months")
```

```{r}
summary(BSE_2019x)
closing_price <- as.xts(data.frame(BSEr = BSE_2019x[, "Close"],BSE100r = BSE100_2019x[, "Close"], 
                                   BSEAUTOr = BSEAUTO_2019x[, "Close"]))
head(closing_price)
```

```{r}
plot(as.zoo(closing_price), screens = 1, lty = 1:3, xlab = "Date", ylab = "Closing Price")
legend("topleft", c("BSEr", "BSE100r", "BSEAUTOr"), lty = 1:3, cex = 0.5)
```

```{r}
returns <- apply(closing_price, 1, function(x) {x / closing_price[1,]}) %>% 
  t %>% as.xts
summary(returns)
plot(as.zoo(returns), screens = 1, lty = 1:3, xlab = "Date", ylab = "Return")
legend("topleft", c("BSEr", "BSE100r", "BSEAUTOr"), lty = 1:3, cex = 0.5)
```

